// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIc_pzi_LAixvc9iBcpzrbqdXHCQlQXFg',
    appId: '1:142259917347:web:d8d6bf824881b6778c1796',
    messagingSenderId: '142259917347',
    projectId: 'sentimo-2f047',
    authDomain: 'sentimo-2f047.firebaseapp.com',
    storageBucket: 'sentimo-2f047.firebasestorage.app',
    measurementId: 'G-HWW10NWR0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuINlVliYRQvBwh9vWGfTIC2IZLvt87OE',
    appId: '1:142259917347:android:aac923b6a1c84c088c1796',
    messagingSenderId: '142259917347',
    projectId: 'sentimo-2f047',
    storageBucket: 'sentimo-2f047.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbR0eLvVylmE_c9Dc1pLF4ubDQcHEdWdI',
    appId: '1:142259917347:ios:fd8cae1c090c166e8c1796',
    messagingSenderId: '142259917347',
    projectId: 'sentimo-2f047',
    storageBucket: 'sentimo-2f047.firebasestorage.app',
    iosBundleId: 'com.example.sentimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbR0eLvVylmE_c9Dc1pLF4ubDQcHEdWdI',
    appId: '1:142259917347:ios:fd8cae1c090c166e8c1796',
    messagingSenderId: '142259917347',
    projectId: 'sentimo-2f047',
    storageBucket: 'sentimo-2f047.firebasestorage.app',
    iosBundleId: 'com.example.sentimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIc_pzi_LAixvc9iBcpzrbqdXHCQlQXFg',
    appId: '1:142259917347:web:6be73cb4c3b8b95d8c1796',
    messagingSenderId: '142259917347',
    projectId: 'sentimo-2f047',
    authDomain: 'sentimo-2f047.firebaseapp.com',
    storageBucket: 'sentimo-2f047.firebasestorage.app',
    measurementId: 'G-G4062YESJ2',
  );
}
